services:
  nginx:
    image: nginx:1.27.2-alpine
    ports:
      - 8080:8080
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - public
    depends_on:
      - atlecta_api

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # ports:
    #   - 5433:5432
    networks:
      - private
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 60s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: atlecta_user # WARNING: WTF IS THIS
      MINIO_ROOT_PASSWORD: atlecta_password # WARNING: WTF IS THIS
    volumes:
      - minio-storage:/data
    networks:
      - private
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"] # Enable AOF persistence
    restart: always
    networks:
      - private

  atlecta_api:
    image: atlecta_api:latest
    build: .
    # ports:
    #   - 8080:8080
    depends_on:
      - postgres
      - minio
      - redis
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - private
      - public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://atlecta_api:8080/healthcheck"]
      interval: 240s
      timeout: 10s
      retries: 1

volumes:
  postgres-data:
  minio-storage:
  redis-data:

configs:
  nginx_config:
    file: ${NGINX_CONF_PATH}

networks:
  public:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"
