services:
  nginx:
    image: nginx:1.27.2-alpine
    ports:
      - 8080:8080
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - public
    depends_on:
      - atlecta_api

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # ports:
    #   - 5433:5432
    networks:
      - private
    volumes:
      - postgres_data:/var/lib/postgresql/data

  atlecta_api:
    image: atlecta_api:latest
    build: .
    # ports:
    #   - 8080:8080
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - private
      - public

volumes:
  postgres_data:

configs:
  nginx_config:
    file: ./nginx.conf

networks:
  public:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"
