"""UserProfileImage

Revision ID: 23516d3e8300
Revises: d1297de0cdfb
Create Date: 2025-05-06 15:20:52.295445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23516d3e8300'
down_revision: Union[str, None] = 'd1297de0cdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False, comment='URL or path to the stored image file'),
    sa.Column('is_profile_picture', sa.Boolean(), nullable=False, comment='Is this the main profile picture?'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='URL or path to the stored image file'),
    sa.Column('is_profile_picture', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is this the main profile picture?'),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], name='user_image_user_profile_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_image_pkey')
    )
    op.drop_table('user_profile_image')
    # ### end Alembic commands ###
