"""Added field 'name' to SportObject table

Revision ID: 3867c89bae17
Revises: ea9487ab8c22
Create Date: 2024-05-06 20:47:01.099487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3867c89bae17'
down_revision: Union[str, None] = 'ea9487ab8c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_object', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport_object', 'name')
    # ### end Alembic commands ###
