"""Deleted test field and use_alter in profile_table

Revision ID: 3add8a864151
Revises: fbb3ed88f0ab
Create Date: 2024-04-25 00:32:11.940272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3add8a864151'
down_revision: Union[str, None] = 'fbb3ed88f0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('test_field', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
