"""OAuth Account table

Revision ID: 3eac6e8c4468
Revises: 7c7cd7aba85a
Create Date: 2025-04-22 12:41:48.445868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics

# revision identifiers, used by Alembic.
revision: str = '3eac6e8c4468'
down_revision: Union[str, None] = '7c7cd7aba85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_account',
                    sa.Column(
                        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column(
                        'id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('oauth_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('access_token', sa.String(
                        length=1024), nullable=False),
                    sa.Column('expires_at', sa.Integer(), nullable=True),
                    sa.Column('refresh_token', sa.String(
                        length=1024), nullable=True),
                    sa.Column('account_id', sa.String(
                        length=320), nullable=False),
                    sa.Column('account_email', sa.String(
                        length=320), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user_account.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_oauth_account_account_id'),
                    'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'),
                    'oauth_account', ['oauth_name'], unique=False)
    op.alter_column('sport_object_image', 'id',
                    existing_type=sa.UUID(),
                    server_default=None,
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sport_object_image', 'id',
                    existing_type=sa.UUID(),
                    server_default=sa.text('gen_random_uuid()'),
                    existing_nullable=False)
    op.drop_index(op.f('ix_oauth_account_oauth_name'),
                  table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'),
                  table_name='oauth_account')
    op.drop_table('oauth_account')
    # ### end Alembic commands ###
