"""Changed SRID from 4326 to 3857 (from lat/long to google maps style)

Revision ID: 54bdfb168704
Revises: fbff1c13a3ac
Create Date: 2025-05-15 21:42:09.041677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2.types

# revision identifiers, used by Alembic.
revision: str = '54bdfb168704'
down_revision: Union[str, None] = 'fbff1c13a3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sport_object', 'location',
                    existing_type=geoalchemy2.types.Geography(
                        geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
                    type_=geoalchemy2.types.Geometry(
                        geometry_type='POINT', srid=3857, from_text='ST_GeogFromText', name='geometry'),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sport_object', 'location',
                    existing_type=geoalchemy2.types.Geometry(
                        geometry_type='POINT', srid=3857, from_text='ST_GeogFromText', name='geometry'),
                    type_=geoalchemy2.types.Geography(
                        geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
                    existing_nullable=True,
                    postgresql_using='ST_Transform(location, 4326)::geography')
    # ### end Alembic commands ###
