"""Changed added uuid.uuid4 as a default value for user_profile_image.id

Revision ID: 6f9f3cbdb28d
Revises: ae066c78b689
Create Date: 2025-05-08 18:38:08.123920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9f3cbdb28d'
down_revision: Union[str, None] = 'ae066c78b689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
