"""SportObjectImage table

Revision ID: 7ab62cc78b74
Revises: cc013f745f9a
Create Date: 2024-12-14 16:30:52.899122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab62cc78b74'
down_revision: Union[str, None] = 'cc013f745f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_object_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_objects_images',
    sa.Column('sport_object_image_id', sa.Uuid(), nullable=False),
    sa.Column('sport_object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_object_id'], ['sport_object.id'], ),
    sa.ForeignKeyConstraint(['sport_object_image_id'], ['sport_object_image.id'], ),
    sa.PrimaryKeyConstraint('sport_object_image_id', 'sport_object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_objects_images')
    op.drop_table('sport_object_image')
    # ### end Alembic commands ###
