"""Frends related tables

Revision ID: a3e60b45dddc
Revises: bbb0a1ef798a
Create Date: 2025-06-14 14:14:38.487479

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e60b45dddc'
down_revision: Union[str, None] = 'bbb0a1ef798a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
                    sa.Column(
                        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column(
                        'friend_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED',
                                                'BLOCKED', name='friendstatus'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['friend_id'], ['user_account.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user_account.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'friend_id'),
                    sa.UniqueConstraint(
                        'user_id', 'friend_id', name='unique_friendship')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###
