"""Changed user_profile_id to user_id

Revision ID: ae066c78b689
Revises: da53ff52204a
Create Date: 2025-05-08 18:03:10.799716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'ae066c78b689'
down_revision: Union[str, None] = 'da53ff52204a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile_image', sa.Column(
        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.drop_constraint('user_profile_image_user_profile_id_fkey',
                       'user_profile_image', type_='foreignkey')
    op.create_foreign_key(None, 'user_profile_image', 'user_profile', [
                          'user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('user_profile_image', 'user_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile_image', sa.Column(
        'user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_profile_image', type_='foreignkey')
    op.create_foreign_key('user_profile_image_user_profile_id_fkey', 'user_profile_image',
                          'user_profile', ['user_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_profile_image', 'user_id')
    # ### end Alembic commands ###
