"""Inventory and SportObjectInventory table

Revision ID: bbb0a1ef798a
Revises: c69d09f68917
Create Date: 2025-06-13 19:34:52.087509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb0a1ef798a'
down_revision: Union[str, None] = 'c69d09f68917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('sport_object_inventory',
                    sa.Column('inventory_id', sa.Integer(), nullable=False),
                    sa.Column('sport_object_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['inventory_id'], ['inventory.id'], ),
                    sa.ForeignKeyConstraint(['sport_object_id'], [
                                            'sport_object.id'], ),
                    sa.PrimaryKeyConstraint('inventory_id', 'sport_object_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_object_inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
