"""Created sports tables

Revision ID: c584e737e905
Revises: 
Create Date: 2024-04-25 00:19:52.916934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c584e737e905'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('sport_object',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('x_coord', sa.Numeric(
                        precision=17, scale=15), nullable=False),
                    sa.Column('y_coord', sa.Numeric(
                        precision=18, scale=15), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sports_objects_tags',
                    sa.Column('sport_id', sa.Integer(), nullable=False),
                    sa.Column('sport_object_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
                    sa.ForeignKeyConstraint(['sport_object_id'], [
                                            'sport_object.id'], ),
                    sa.PrimaryKeyConstraint('sport_id', 'sport_object_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sports_objects_tags')
    op.drop_table('sport_object')
    op.drop_table('sport')
    # ### end Alembic commands ###
