"""Chat module tables

Revision ID: c69d09f68917
Revises: 44736b47e09c
Create Date: 2025-06-11 16:22:48.116414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics

# revision identifiers, used by Alembic.
revision: str = 'c69d09f68917'
down_revision: Union[str, None] = '44736b47e09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('file_url', sa.String(), nullable=False),
                    sa.Column('file_type', sa.String(), nullable=False),
                    sa.Column('uploaded_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chat',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('group',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column(
                        'admin_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['admin_id'], ['user_account.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chat_member',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('chat_id', sa.Uuid(), nullable=True),
                    sa.Column('group_id', sa.Uuid(), nullable=True),
                    sa.Column(
                        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('is_moderator', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user_account.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('message',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('chat_id', sa.Uuid(), nullable=True),
                    sa.Column('group_id', sa.Uuid(), nullable=True),
                    sa.Column(
                        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('content', sa.String(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('attachment_id', sa.Uuid(), nullable=True),
                    sa.Column('sport_object_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['attachment_id'], ['attachment.id'], ),
                    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.ForeignKeyConstraint(['sport_object_id'], [
                                            'sport_object.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user_account.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chat_member')
    op.drop_table('group')
    op.drop_table('chat')
    op.drop_table('attachment')
    # ### end Alembic commands ###
