"""Added location for PostGIS support (x and y coords to be converted to location)

Revision ID: c9e3a9bef81a
Revises: 6f9f3cbdb28d
Create Date: 2025-05-13 21:00:58.215065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision: str = 'c9e3a9bef81a'
down_revision: Union[str, None] = '6f9f3cbdb28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('sport_object', sa.Column('location', Geometry(
        geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('sport_object', 'x_coord',
                    existing_type=sa.NUMERIC(precision=17, scale=15),
                    nullable=False)
    op.alter_column('sport_object', 'y_coord',
                    existing_type=sa.NUMERIC(precision=18, scale=15),
                    nullable=False)
    # op.create_index('idx_sport_object_location', 'sport_object', [
    #                 'location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_sport_object_location',
    #               table_name='sport_object', postgresql_using='gist')
    op.alter_column('sport_object', 'y_coord',
                    existing_type=sa.NUMERIC(precision=18, scale=15),
                    nullable=True)
    op.alter_column('sport_object', 'x_coord',
                    existing_type=sa.NUMERIC(precision=17, scale=15),
                    nullable=True)
    op.drop_column('sport_object', 'location')
    # op.create_table('spatial_ref_sys',
    #                 sa.Column('srid', sa.INTEGER(),
    #                           autoincrement=False, nullable=False),
    #                 sa.Column('auth_name', sa.VARCHAR(length=256),
    #                           autoincrement=False, nullable=True),
    #                 sa.Column('auth_srid', sa.INTEGER(),
    #                           autoincrement=False, nullable=True),
    #                 sa.Column('srtext', sa.VARCHAR(length=2048),
    #                           autoincrement=False, nullable=True),
    #                 sa.Column('proj4text', sa.VARCHAR(length=2048),
    #                           autoincrement=False, nullable=True),
    #                 sa.CheckConstraint('srid > 0 AND srid <= 998999',
    #                                    name='spatial_ref_sys_srid_check'),
    #                 sa.PrimaryKeyConstraint(
    #                     'srid', name='spatial_ref_sys_pkey')
    #                 )
    # ### end Alembic commands ###
