"""Chaged sports_objects_tags to sport_objects_tags

Revision ID: cc013f745f9a
Revises: 3867c89bae17
Create Date: 2024-08-21 22:01:51.354583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc013f745f9a'
down_revision: Union[str, None] = '3867c89bae17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_objects_tags',
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('sport_object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['sport_object_id'], ['sport_object.id'], ),
    sa.PrimaryKeyConstraint('sport_id', 'sport_object_id')
    )
    op.drop_table('sports_objects_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports_objects_tags',
    sa.Column('sport_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sport_object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], name='sports_objects_tags_sport_id_fkey'),
    sa.ForeignKeyConstraint(['sport_object_id'], ['sport_object.id'], name='sports_objects_tags_sport_object_id_fkey'),
    sa.PrimaryKeyConstraint('sport_id', 'sport_object_id', name='sports_objects_tags_pkey')
    )
    op.drop_table('sport_objects_tags')
    # ### end Alembic commands ###
