"""Changed 'UserProfile.user' to 'UserProfile.user_account'

Revision ID: d1297de0cdfb
Revises: 3eac6e8c4468
Create Date: 2025-04-25 20:39:27.948351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1297de0cdfb'
down_revision: Union[str, None] = '3eac6e8c4468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
