"""Changed x_coord and y_coord to location for PostGIS support

Revision ID: dcfdb85eac9a
Revises: 6f9f3cbdb28d
Create Date: 2025-05-13 20:33:44.600618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision: str = 'dcfdb85eac9a'
down_revision: Union[str, None] = '6f9f3cbdb28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_object', sa.Column('location', Geometry(
        geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_sport_object_location', 'sport_object', [
                    'location'], unique=False, postgresql_using='gist')
    op.drop_column('sport_object', 'y_coord')
    op.drop_column('sport_object', 'x_coord')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_object', sa.Column('x_coord', sa.NUMERIC(
        precision=17, scale=15), autoincrement=False, nullable=False))
    op.add_column('sport_object', sa.Column('y_coord', sa.NUMERIC(
        precision=18, scale=15), autoincrement=False, nullable=False))
    op.drop_index('idx_sport_object_location',
                  table_name='sport_object', postgresql_using='gist')
    op.drop_column('sport_object', 'location')
    # ### end Alembic commands ###
