"""Changed name of user table to user_account

Revision ID: ea9487ab8c22
Revises: 3e0e58d88673
Create Date: 2024-04-28 01:24:24.679180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9487ab8c22'
down_revision: Union[str, None] = '3e0e58d88673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.rename_table('user', 'user_account')
    op.create_index(op.f('ix_user_account_email'),
                    'user_account', ['email'], unique=True)
    op.drop_constraint('user_profile_user_id_fkey',
                       'user_profile', type_='foreignkey')
    op.create_foreign_key(None, 'user_profile',
                          'user_account', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_account', 'user')
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.create_foreign_key('user_profile_user_id_fkey',
                          'user_profile', 'user', ['user_id'], ['id'])
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    # ### end Alembic commands ###
