"""Changed Geometry to Geography (to keep distance in meters)

Revision ID: fbff1c13a3ac
Revises: c9e3a9bef81a
Create Date: 2025-05-15 20:36:13.286718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2.types

# revision identifiers, used by Alembic.
revision: str = 'fbff1c13a3ac'
down_revision: Union[str, None] = 'c9e3a9bef81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.alter_column('sport_object', 'y_coord',
                    existing_type=sa.NUMERIC(precision=18, scale=15),
                    type_=sa.Numeric(precision=17, scale=15),
                    existing_nullable=False)
    op.alter_column('sport_object', 'x_coord',
                    existing_type=sa.NUMERIC(precision=17, scale=15),
                    type_=sa.Numeric(precision=18, scale=15),
                    existing_nullable=False)
    op.alter_column('sport_object', 'location',
                    existing_type=geoalchemy2.types.Geometry(
                        geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
                    type_=geoalchemy2.types.Geography(
                        geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sport_object', 'location',
                    existing_type=geoalchemy2.types.Geography(
                        geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
                    type_=geoalchemy2.types.Geometry(
                        geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
                    existing_nullable=True)
    op.alter_column('sport_object', 'x_coord',
                    existing_type=sa.Numeric(precision=18, scale=15),
                    type_=sa.NUMERIC(precision=17, scale=15),
                    existing_nullable=False)
    op.alter_column('sport_object', 'y_coord',
                    existing_type=sa.Numeric(precision=17, scale=15),
                    type_=sa.NUMERIC(precision=18, scale=15),
                    existing_nullable=False)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
