# Run poetry pytest on pull requests and push to main

# NOTE: If you don't specify `branches: [main]`, then this actions runs twice on pull requests
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ikalnytskyi/action-setup-postgres@v6
        with:
          username: ${{ secrets.DB_USER_TEST }}
          password: ${{ secrets.DB_PASSWORD_TEST }}
          database: ${{ secrets.DB_NAME_TEST }}
          port: ${{ secrets.DB_PORT_TEST }}
          postgres-version: "16"
        id: postgres

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.8.3-0

      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - run: poetry install --no-interaction

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          evnkey_DEV_MODE: false
          envkey_DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
          envkey_DB_PORT_TEST: ${{ secrets.DB_PORT_TEST }}
          envkey_DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
          envkey_DB_USER_TEST: ${{ secrets.DB_USER_TEST }}
          envkey_DB_PASSWORD_TEST: ${{ secrets.DB_PASSWORD_TEST }}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          file_name: .env

      - run: poetry run pytest

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          evnkey_DEV_MODE: false
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          envkey_NGINX_CONF_PATH: ${{ secrets.NGINX_CONF_PATH }}
          file_name: .env

      - name: Stop containers and networks
        run: docker-compose down

      - name: Start docker-compose
        run: docker compose up -d --build

      - name: Clear dungling images
        run: docker system prune -f
